networks:
  rag-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: rag-network

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - COLLECTION_NAME=rag_collection
      - DOCS_PATH=/app/documents
    volumes:
      - ./backend/documents:/app/documents
    depends_on:
      - qdrant
      - redis
    networks:
      rag-network:
        aliases:
          - backend-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    extra_hosts:
      - "backend:127.0.0.1"

  frontend:
    build: ./frontend
    container_name: rag-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      rag-network:
        aliases:
          - frontend-service
    extra_hosts:
      - "backend:127.0.0.1"