version: "3.8"

networks:
  rag-network:
    driver: bridge

services:

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rag-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=/models
    volumes:
      - ollama_models:/models
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - rag-network


  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - rag-network

  embedding-worker:
    build: ./embedding-worker
    container_name: embedding-worker
    restart: unless-stopped
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DOCS_PATH=/documents
      - EMBEDDING_MODEL=BAAI/bge-m3
    volumes:
      - ./documents:/documents
    depends_on:
      - qdrant
    networks:
      - rag-network

  rag-backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - COLLECTION_NAME=rag_collection
      - DOCS_PATH=/app/documents
    volumes:
      - ./backend/documents:/app/documents
    depends_on:
      - qdrant
      - redis
    networks:
      - rag-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build: ./frontend
    container_name: rag-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - rag-network

volumes:
  ollama_models:
  qdrant_data:
